(defpackage :qstar
    (:documentation "quadtree-based 2-D collision detection and A-star pathfinding")
  (:use :common-lisp) 
  (:export
   *buffer-height*
   *buffer-width*
   *default-quadtree-depth*
   *path-grid-resolution*
   *quadtree*
   *quadtree-depth*
   address-to-waypoint
   bounding-box-contains
   build-quadtree
   cfloat
   collide
   collide-objects
   collide-objects*
   colliding-with-p
   collision-type
   create-path
   find-path
   find-path-waypoints
   handle-collision
   heading
   height
   last-x
   last-y
   last-z
   leafp
   make-quadtree
   obstructed
   path
   path-finder
   quadrille
   quadtree
   quadtree-collide
   quadtree-contains
   quadtree-delete
   quadtree-delete-maybe
   quadtree-fill
   quadtree-insert
   quadtree-insert-maybe
   quadtree-map-collisions
   quadtree-node
   quadtree-process
   quadtree-search
   update-bounding-box
   valid-bounding-box-p
   width
   will-obstruct-p
   with-quadtree
   within-buffer-boundaries-p
   within-extents
   x
   y
   z
   ))

