(defpackage :qstar
    (:documentation "quadtree-based 2-D collision detection and A-star pathfinding")
  (:use :common-lisp) 
  (:export
   *buffer-height*
   *buffer-width*
   *default-quadtree-depth*
   *path-grid-resolution*
   *quadtree*
   *quadtree-depth*
   address-to-waypoint
   aim
   aim-at
   bounding-box
   bounding-box-contains
   build-quadtree
   center-point
   cfloat
   clear-saved-location
   collide
   collide-objects
   collide-objects*
   colliding-with-bounding-box-p
   colliding-with-p
   colliding-with-p
   colliding-with-rectangle-p
   collision-type
   create-path
   distance-between
   find-path
   find-path-waypoints
   forward
   handle-collision
   heading
   heading-between
   heading-to-thing
   height
   last-x
   last-y
   last-z
   leafp
   make-quadtree
   move
   move-to
   move-toward
   obstructed
   path
   path-finder
   quadrille
   quadtree
   quadtree-collide
   quadtree-contains
   quadtree-delete
   quadtree-delete-maybe
   quadtree-fill
   quadtree-insert
   quadtree-insert-maybe
   quadtree-map-collisions
   quadtree-node
   quadtree-process
   quadtree-search
   rectangle-in-rectangle-p
   resize
   restore-location
   save-location
   step-coordinates
   step-toward-heading
   turn-left
   turn-right
   update-bounding-box
   valid-bounding-box-p
   width
   will-obstruct-p
   with-quadtree
   within-buffer-boundaries-p
   within-extents
   x
   y
   z
   ))

